## Binary case (two hidden states): map land uses to crops, pasture
map_landuse_to_S_binary <- c("?"=NA,
                             "abertura"="pasture",  # Eduardo: sounds like transitioning area (deforested not yet put into use)
                             "algodăo"="crops",  # Cotton
                             "amendoim"="crops",  # Peanut
                             "arroz"="crops",  # Rice
                             "crotalária"="crops",  # Eduardo: vegetable
                             "enleiramento"="crops",  # Eduardo: part of haymaking process
                             "eucalipto"="crops",  # Eduardo: planted trees, typically used to produce cellulose
                             "feijao"="crops",  # Beans
                             "juquira"="pasture",  # Eduardo: bush that appears predominantly in abandoned areas, maybe fallow land
                             "Mata"=NA,
                             "milheto"="crops",
                             "milheto/soja"="crops",
                             "milho"="crops",
                             "milho branco"="crops",
                             "nim"="crops",
                             "no data"=NA,
                             "pasto"="pasture",
                             "pasto (brizantăo)"="pasture",
                             "pasto degradado"="pasture",
                             "pasto(b)"="pasture",
                             "pasto/eucalipto"="pasture",
                             "pasto+boi"="pasture",
                             "pipoca"="crops",  # Corn
                             "pousio"="pasture",  # Eduardo: fallow land, may be either for crops or pasture
                             "reflorestamento"=NA,  # Reforestation
                             "soja"="crops",
                             "soja precoce"="crops")

## Ternary case (three hidden states): map land uses to soy, non-soy crops, pasture
map_landuse_to_S_ternary <- c("?"=NA,
                              "abertura"="pasture",  # Eduardo: sounds like transitioning area (deforested not yet put into use)
                              "algodăo"="non-soy crops",  # Cotton
                              "amendoim"="non-soy crops",  # Peanut
                              "arroz"="non-soy crops",  # Rice
                              "crotalária"="non-soy crops",  # Eduardo: vegetable
                              "enleiramento"="non-soy crops",  # Eduardo: part of haymaking process
                              "eucalipto"="non-soy crops",  # Eduardo: planted trees, typically used to produce cellulose
                              "feijao"="non-soy crops",  # Beans
                              "juquira"="pasture",  # Eduardo: bush that appears predominantly in abandoned areas, maybe fallow land
                              "Mata"=NA,
                              "milheto"="non-soy crops",
                              "milheto/soja"="non-soy crops",
                              "milho"="non-soy crops",
                              "milho branco"="non-soy crops",
                              "nim"="non-soy crops",
                              "no data"=NA,
                              "pasto"="pasture",
                              "pasto (brizantăo)"="pasture",
                              "pasto degradado"="pasture",
                              "pasto(b)"="pasture",
                              "pasto/eucalipto"="pasture",
                              "pasto+boi"="pasture",
                              "pipoca"="non-soy crops",  # Corn
                              "pousio"="pasture",  # Eduardo: fallow land, may be either for crops or pasture
                              "reflorestamento"=NA,  # Reforestation
                              "soja"="soy",
                              "soja precoce"="soy")
