name: Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: hidden_markov_model:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Simple Simulation
        run: docker run -v ${{ github.workspace }}:/home/hidden_markov_model hidden_markov_model bash -c "Rscript simulation_simple.R"
